/* Generated by Yosys 0.35+29 (git sha1 ab6c1d368, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* src = "sbox_complete.v:322.1-330.10" *)
module sbox_and(a, b, out);
  (* src = "sbox_complete.v:324.11-324.12" *)
  input a;
  wire a;
  (* src = "sbox_complete.v:324.14-324.15" *)
  input b;
  wire b;
  (* src = "sbox_complete.v:325.12-325.15" *)
  output out;
  wire out;
  assign out = a & b;
endmodule

(* top =  1  *)
(* src = "sbox_complete.v:3.1-300.10" *)
module sbox_complete(clk, state, u0, u1, u2, u3, u4, u5, u6, u7, o0, o1, o2, o3, o4, o5, o6, o7);
  (* src = "sbox_complete.v:5.12-5.15" *)
  input clk;
  wire clk;
  (* src = "sbox_complete.v:19.5-19.6" *)
  wire d;
  (* src = "sbox_complete.v:12.11-12.14" *)
  wire ft1;
  (* src = "sbox_complete.v:12.56-12.60" *)
  wire ft10;
  (* src = "sbox_complete.v:12.62-12.66" *)
  wire ft11;
  (* src = "sbox_complete.v:12.68-12.72" *)
  wire ft12;
  (* src = "sbox_complete.v:12.74-12.78" *)
  wire ft13;
  (* src = "sbox_complete.v:12.80-12.84" *)
  wire ft14;
  (* src = "sbox_complete.v:12.86-12.90" *)
  wire ft15;
  (* src = "sbox_complete.v:12.92-12.96" *)
  wire ft16;
  (* src = "sbox_complete.v:12.98-12.102" *)
  wire ft17;
  (* src = "sbox_complete.v:12.104-12.108" *)
  wire ft18;
  (* src = "sbox_complete.v:12.110-12.114" *)
  wire ft19;
  (* src = "sbox_complete.v:12.16-12.19" *)
  wire ft2;
  (* src = "sbox_complete.v:12.116-12.120" *)
  wire ft20;
  (* src = "sbox_complete.v:12.122-12.126" *)
  wire ft21;
  (* src = "sbox_complete.v:12.128-12.132" *)
  wire ft22;
  (* src = "sbox_complete.v:12.134-12.138" *)
  wire ft23;
  (* src = "sbox_complete.v:12.140-12.144" *)
  wire ft24;
  (* src = "sbox_complete.v:12.146-12.150" *)
  wire ft25;
  (* src = "sbox_complete.v:12.152-12.156" *)
  wire ft26;
  (* src = "sbox_complete.v:12.158-12.162" *)
  wire ft27;
  (* src = "sbox_complete.v:12.21-12.24" *)
  wire ft3;
  (* src = "sbox_complete.v:12.26-12.29" *)
  wire ft4;
  (* src = "sbox_complete.v:12.31-12.34" *)
  wire ft5;
  (* src = "sbox_complete.v:12.36-12.39" *)
  wire ft6;
  (* src = "sbox_complete.v:12.41-12.44" *)
  wire ft7;
  (* src = "sbox_complete.v:12.46-12.49" *)
  wire ft8;
  (* src = "sbox_complete.v:12.51-12.54" *)
  wire ft9;
  (* src = "sbox_complete.v:17.6-17.8" *)
  wire l0;
  (* src = "sbox_complete.v:17.10-17.12" *)
  wire l1;
  (* src = "sbox_complete.v:17.46-17.49" *)
  wire l10;
  (* src = "sbox_complete.v:17.51-17.54" *)
  wire l11;
  (* src = "sbox_complete.v:17.56-17.59" *)
  wire l12;
  (* src = "sbox_complete.v:17.61-17.64" *)
  wire l13;
  (* src = "sbox_complete.v:17.66-17.69" *)
  wire l14;
  (* src = "sbox_complete.v:17.71-17.74" *)
  wire l15;
  (* src = "sbox_complete.v:17.76-17.79" *)
  wire l16;
  (* src = "sbox_complete.v:17.81-17.84" *)
  wire l17;
  (* src = "sbox_complete.v:17.86-17.89" *)
  wire l18;
  (* src = "sbox_complete.v:17.91-17.94" *)
  wire l19;
  (* src = "sbox_complete.v:17.14-17.16" *)
  wire l2;
  (* src = "sbox_complete.v:17.96-17.99" *)
  wire l20;
  (* src = "sbox_complete.v:17.101-17.104" *)
  wire l21;
  (* src = "sbox_complete.v:17.106-17.109" *)
  wire l22;
  (* src = "sbox_complete.v:17.111-17.114" *)
  wire l23;
  (* src = "sbox_complete.v:17.116-17.119" *)
  wire l24;
  (* src = "sbox_complete.v:17.121-17.124" *)
  wire l25;
  (* src = "sbox_complete.v:17.126-17.129" *)
  wire l26;
  (* src = "sbox_complete.v:17.131-17.134" *)
  wire l27;
  (* src = "sbox_complete.v:17.136-17.139" *)
  wire l28;
  (* src = "sbox_complete.v:17.141-17.144" *)
  wire l29;
  (* src = "sbox_complete.v:17.18-17.20" *)
  wire l3;
  (* src = "sbox_complete.v:17.22-17.24" *)
  wire l4;
  (* src = "sbox_complete.v:17.26-17.28" *)
  wire l5;
  (* src = "sbox_complete.v:17.30-17.32" *)
  wire l6;
  (* src = "sbox_complete.v:17.34-17.36" *)
  wire l7;
  (* src = "sbox_complete.v:17.38-17.40" *)
  wire l8;
  (* src = "sbox_complete.v:17.42-17.44" *)
  wire l9;
  (* src = "sbox_complete.v:14.10-14.12" *)
  wire m1;
  (* src = "sbox_complete.v:14.46-14.49" *)
  wire m10;
  (* src = "sbox_complete.v:14.51-14.54" *)
  wire m11;
  (* src = "sbox_complete.v:14.56-14.59" *)
  wire m12;
  (* src = "sbox_complete.v:14.61-14.64" *)
  wire m13;
  (* src = "sbox_complete.v:14.66-14.69" *)
  wire m14;
  (* src = "sbox_complete.v:14.71-14.74" *)
  wire m15;
  (* src = "sbox_complete.v:14.76-14.79" *)
  wire m16;
  (* src = "sbox_complete.v:14.81-14.84" *)
  wire m17;
  (* src = "sbox_complete.v:14.86-14.89" *)
  wire m18;
  (* src = "sbox_complete.v:14.91-14.94" *)
  wire m19;
  (* src = "sbox_complete.v:14.14-14.16" *)
  wire m2;
  (* src = "sbox_complete.v:14.96-14.99" *)
  wire m20;
  (* src = "sbox_complete.v:14.101-14.104" *)
  wire m21;
  (* src = "sbox_complete.v:14.106-14.109" *)
  wire m22;
  (* src = "sbox_complete.v:14.111-14.114" *)
  wire m23;
  (* src = "sbox_complete.v:14.116-14.119" *)
  wire m24;
  (* src = "sbox_complete.v:14.121-14.124" *)
  wire m25;
  (* src = "sbox_complete.v:14.126-14.129" *)
  wire m26;
  (* src = "sbox_complete.v:14.131-14.134" *)
  wire m27;
  (* src = "sbox_complete.v:14.136-14.139" *)
  wire m28;
  (* src = "sbox_complete.v:14.141-14.144" *)
  wire m29;
  (* src = "sbox_complete.v:14.18-14.20" *)
  wire m3;
  (* src = "sbox_complete.v:14.146-14.149" *)
  wire m30;
  (* src = "sbox_complete.v:14.151-14.154" *)
  wire m31;
  (* src = "sbox_complete.v:14.156-14.159" *)
  wire m32;
  (* src = "sbox_complete.v:14.161-14.164" *)
  wire m33;
  (* src = "sbox_complete.v:14.166-14.169" *)
  wire m34;
  (* src = "sbox_complete.v:14.171-14.174" *)
  wire m35;
  (* src = "sbox_complete.v:14.176-14.179" *)
  wire m36;
  (* src = "sbox_complete.v:14.181-14.184" *)
  wire m37;
  (* src = "sbox_complete.v:14.186-14.189" *)
  wire m38;
  (* src = "sbox_complete.v:14.191-14.194" *)
  wire m39;
  (* src = "sbox_complete.v:14.22-14.24" *)
  wire m4;
  (* src = "sbox_complete.v:14.196-14.199" *)
  wire m40;
  (* src = "sbox_complete.v:14.201-14.204" *)
  wire m41;
  (* src = "sbox_complete.v:14.206-14.209" *)
  wire m42;
  (* src = "sbox_complete.v:14.211-14.214" *)
  wire m43;
  (* src = "sbox_complete.v:14.216-14.219" *)
  wire m44;
  (* src = "sbox_complete.v:14.221-14.224" *)
  wire m45;
  (* src = "sbox_complete.v:14.226-14.229" *)
  wire m46;
  (* src = "sbox_complete.v:14.231-14.234" *)
  wire m47;
  (* src = "sbox_complete.v:14.236-14.239" *)
  wire m48;
  (* src = "sbox_complete.v:14.241-14.244" *)
  wire m49;
  (* src = "sbox_complete.v:14.26-14.28" *)
  wire m5;
  (* src = "sbox_complete.v:14.246-14.249" *)
  wire m50;
  (* src = "sbox_complete.v:14.251-14.254" *)
  wire m51;
  (* src = "sbox_complete.v:14.256-14.259" *)
  wire m52;
  (* src = "sbox_complete.v:14.261-14.264" *)
  wire m53;
  (* src = "sbox_complete.v:14.266-14.269" *)
  wire m54;
  (* src = "sbox_complete.v:14.271-14.274" *)
  wire m55;
  (* src = "sbox_complete.v:14.276-14.279" *)
  wire m56;
  (* src = "sbox_complete.v:14.281-14.284" *)
  wire m57;
  (* src = "sbox_complete.v:14.286-14.289" *)
  wire m58;
  (* src = "sbox_complete.v:14.291-14.294" *)
  wire m59;
  (* src = "sbox_complete.v:14.30-14.32" *)
  wire m6;
  (* src = "sbox_complete.v:14.296-14.299" *)
  wire m60;
  (* src = "sbox_complete.v:14.301-14.304" *)
  wire m61;
  (* src = "sbox_complete.v:14.306-14.309" *)
  wire m62;
  (* src = "sbox_complete.v:14.311-14.314" *)
  wire m63;
  (* src = "sbox_complete.v:14.34-14.36" *)
  wire m7;
  (* src = "sbox_complete.v:14.38-14.40" *)
  wire m8;
  (* src = "sbox_complete.v:14.42-14.44" *)
  wire m9;
  (* src = "sbox_complete.v:8.12-8.14" *)
  output o0;
  wire o0;
  (* src = "sbox_complete.v:8.16-8.18" *)
  output o1;
  wire o1;
  (* src = "sbox_complete.v:8.20-8.22" *)
  output o2;
  wire o2;
  (* src = "sbox_complete.v:8.24-8.26" *)
  output o3;
  wire o3;
  (* src = "sbox_complete.v:8.28-8.30" *)
  output o4;
  wire o4;
  (* src = "sbox_complete.v:8.32-8.34" *)
  output o5;
  wire o5;
  (* src = "sbox_complete.v:8.36-8.38" *)
  output o6;
  wire o6;
  (* src = "sbox_complete.v:8.40-8.42" *)
  output o7;
  wire o7;
  (* src = "sbox_complete.v:15.6-15.8" *)
  wire p0;
  (* src = "sbox_complete.v:15.10-15.12" *)
  wire p1;
  (* src = "sbox_complete.v:15.46-15.49" *)
  wire p10;
  (* src = "sbox_complete.v:15.51-15.54" *)
  wire p11;
  (* src = "sbox_complete.v:15.56-15.59" *)
  wire p12;
  (* src = "sbox_complete.v:15.61-15.64" *)
  wire p13;
  (* src = "sbox_complete.v:15.66-15.69" *)
  wire p14;
  (* src = "sbox_complete.v:15.71-15.74" *)
  wire p15;
  (* src = "sbox_complete.v:15.76-15.79" *)
  wire p16;
  (* src = "sbox_complete.v:15.81-15.84" *)
  wire p17;
  (* src = "sbox_complete.v:15.86-15.89" *)
  wire p18;
  (* src = "sbox_complete.v:15.91-15.94" *)
  wire p19;
  (* src = "sbox_complete.v:15.14-15.16" *)
  wire p2;
  (* src = "sbox_complete.v:15.96-15.99" *)
  wire p20;
  (* src = "sbox_complete.v:15.101-15.104" *)
  wire p22;
  (* src = "sbox_complete.v:15.106-15.109" *)
  wire p23;
  (* src = "sbox_complete.v:15.111-15.114" *)
  wire p24;
  (* src = "sbox_complete.v:15.116-15.119" *)
  wire p25;
  (* src = "sbox_complete.v:15.121-15.124" *)
  wire p26;
  (* src = "sbox_complete.v:15.126-15.129" *)
  wire p27;
  (* src = "sbox_complete.v:15.131-15.134" *)
  wire p28;
  (* src = "sbox_complete.v:15.136-15.139" *)
  wire p29;
  (* src = "sbox_complete.v:15.18-15.20" *)
  wire p3;
  (* src = "sbox_complete.v:15.22-15.24" *)
  wire p4;
  (* src = "sbox_complete.v:15.26-15.28" *)
  wire p5;
  (* src = "sbox_complete.v:15.30-15.32" *)
  wire p6;
  (* src = "sbox_complete.v:15.34-15.36" *)
  wire p7;
  (* src = "sbox_complete.v:15.38-15.40" *)
  wire p8;
  (* src = "sbox_complete.v:15.42-15.44" *)
  wire p9;
  (* src = "sbox_complete.v:16.10-16.13" *)
  wire r13;
  (* src = "sbox_complete.v:16.15-16.18" *)
  wire r17;
  (* src = "sbox_complete.v:16.20-16.23" *)
  wire r18;
  (* src = "sbox_complete.v:16.25-16.28" *)
  wire r19;
  (* src = "sbox_complete.v:16.6-16.8" *)
  wire r5;
  (* src = "sbox_complete.v:13.11-13.14" *)
  wire rt1;
  (* src = "sbox_complete.v:13.56-13.60" *)
  wire rt10;
  (* src = "sbox_complete.v:13.74-13.78" *)
  wire rt13;
  (* src = "sbox_complete.v:13.80-13.84" *)
  wire rt14;
  (* src = "sbox_complete.v:13.86-13.90" *)
  wire rt15;
  (* src = "sbox_complete.v:13.92-13.96" *)
  wire rt16;
  (* src = "sbox_complete.v:13.98-13.102" *)
  wire rt17;
  (* src = "sbox_complete.v:13.110-13.114" *)
  wire rt19;
  (* src = "sbox_complete.v:13.16-13.19" *)
  wire rt2;
  (* src = "sbox_complete.v:13.116-13.120" *)
  wire rt20;
  (* src = "sbox_complete.v:13.128-13.132" *)
  wire rt22;
  (* src = "sbox_complete.v:13.134-13.138" *)
  wire rt23;
  (* src = "sbox_complete.v:13.140-13.144" *)
  wire rt24;
  (* src = "sbox_complete.v:13.146-13.150" *)
  wire rt25;
  (* src = "sbox_complete.v:13.152-13.156" *)
  wire rt26;
  (* src = "sbox_complete.v:13.158-13.162" *)
  wire rt27;
  (* src = "sbox_complete.v:13.21-13.24" *)
  wire rt3;
  (* src = "sbox_complete.v:13.26-13.29" *)
  wire rt4;
  (* src = "sbox_complete.v:13.36-13.39" *)
  wire rt6;
  (* src = "sbox_complete.v:13.46-13.49" *)
  wire rt8;
  (* src = "sbox_complete.v:13.51-13.54" *)
  wire rt9;
  (* src = "sbox_complete.v:21.6-21.8" *)
  wire s0;
  (* src = "sbox_complete.v:21.10-21.12" *)
  wire s1;
  (* src = "sbox_complete.v:21.14-21.16" *)
  wire s2;
  (* src = "sbox_complete.v:21.18-21.20" *)
  wire s3;
  (* src = "sbox_complete.v:21.22-21.24" *)
  wire s4;
  (* src = "sbox_complete.v:21.26-21.28" *)
  wire s5;
  (* src = "sbox_complete.v:21.30-21.32" *)
  wire s6;
  (* src = "sbox_complete.v:21.34-21.36" *)
  wire s7;
  (* src = "sbox_complete.v:6.11-6.16" *)
  input state;
  wire state;
  (* src = "sbox_complete.v:11.9-11.11" *)
  wire t1;
  (* src = "sbox_complete.v:11.45-11.48" *)
  wire t10;
  (* src = "sbox_complete.v:11.60-11.63" *)
  wire t13;
  (* src = "sbox_complete.v:11.65-11.68" *)
  wire t14;
  (* src = "sbox_complete.v:11.70-11.73" *)
  wire t15;
  (* src = "sbox_complete.v:11.75-11.78" *)
  wire t16;
  (* src = "sbox_complete.v:11.80-11.83" *)
  wire t17;
  (* src = "sbox_complete.v:11.90-11.93" *)
  wire t19;
  (* src = "sbox_complete.v:11.13-11.15" *)
  wire t2;
  (* src = "sbox_complete.v:11.95-11.98" *)
  wire t20;
  (* src = "sbox_complete.v:11.105-11.108" *)
  wire t22;
  (* src = "sbox_complete.v:11.110-11.113" *)
  wire t23;
  (* src = "sbox_complete.v:11.115-11.118" *)
  wire t24;
  (* src = "sbox_complete.v:11.120-11.123" *)
  wire t25;
  (* src = "sbox_complete.v:11.125-11.128" *)
  wire t26;
  (* src = "sbox_complete.v:11.130-11.133" *)
  wire t27;
  (* src = "sbox_complete.v:11.17-11.19" *)
  wire t3;
  (* src = "sbox_complete.v:11.21-11.23" *)
  wire t4;
  (* src = "sbox_complete.v:11.29-11.31" *)
  wire t6;
  (* src = "sbox_complete.v:11.37-11.39" *)
  wire t8;
  (* src = "sbox_complete.v:11.41-11.43" *)
  wire t9;
  (* src = "sbox_complete.v:7.12-7.14" *)
  input u0;
  wire u0;
  (* src = "sbox_complete.v:7.16-7.18" *)
  input u1;
  wire u1;
  (* src = "sbox_complete.v:7.20-7.22" *)
  input u2;
  wire u2;
  (* src = "sbox_complete.v:7.24-7.26" *)
  input u3;
  wire u3;
  (* src = "sbox_complete.v:7.28-7.30" *)
  input u4;
  wire u4;
  (* src = "sbox_complete.v:7.32-7.34" *)
  input u5;
  wire u5;
  (* src = "sbox_complete.v:7.36-7.38" *)
  input u6;
  wire u6;
  (* src = "sbox_complete.v:7.40-7.42" *)
  input u7;
  wire u7;
  (* src = "sbox_complete.v:20.6-20.8" *)
  wire w0;
  (* src = "sbox_complete.v:20.10-20.12" *)
  wire w1;
  (* src = "sbox_complete.v:20.14-20.16" *)
  wire w2;
  (* src = "sbox_complete.v:20.18-20.20" *)
  wire w3;
  (* src = "sbox_complete.v:20.22-20.24" *)
  wire w4;
  (* src = "sbox_complete.v:20.26-20.28" *)
  wire w5;
  (* src = "sbox_complete.v:20.30-20.32" *)
  wire w6;
  (* src = "sbox_complete.v:20.34-20.36" *)
  wire w7;
  (* src = "sbox_complete.v:18.6-18.8" *)
  wire y5;
  assign d = state ? y5 : u7;
  assign o0 = state ? w0 : s0;
  assign o1 = state ? w1 : s1;
  assign o2 = state ? w2 : s2;
  assign o3 = state ? w3 : s3;
  assign o4 = state ? w4 : s4;
  assign o5 = state ? w5 : s5;
  assign o6 = state ? w6 : s6;
  assign o7 = state ? w7 : s7;
  assign t27 = state ? rt27 : ft27;
  assign t26 = state ? rt26 : ft26;
  assign t25 = state ? rt25 : ft25;
  assign t24 = state ? rt24 : ft24;
  assign t23 = state ? rt23 : ft23;
  assign t22 = state ? rt22 : ft22;
  assign t20 = state ? rt20 : ft20;
  assign t19 = state ? rt19 : ft19;
  assign t17 = state ? rt17 : ft17;
  assign t16 = state ? rt16 : ft16;
  assign t15 = state ? rt15 : ft15;
  assign t14 = state ? rt14 : ft14;
  assign t13 = state ? rt13 : ft13;
  assign t10 = state ? rt10 : ft10;
  assign t9 = state ? rt9 : ft9;
  assign t8 = state ? rt8 : ft8;
  assign t6 = state ? rt6 : ft6;
  assign t4 = state ? rt4 : ft4;
  assign t3 = state ? rt3 : ft3;
  assign t2 = state ? rt2 : ft2;
  assign t1 = state ? rt1 : ft1;
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:148.10-148.28" *)
  sbox_and and0 (
    .a(t13),
    .b(t6),
    .out(m1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:149.10-149.28" *)
  sbox_and and1 (
    .a(t23),
    .b(t8),
    .out(m2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:176.10-176.31" *)
  sbox_and and10 (
    .a(m28),
    .b(m27),
    .out(m29)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:177.10-177.31" *)
  sbox_and and11 (
    .a(m26),
    .b(m24),
    .out(m30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:178.10-178.31" *)
  sbox_and and12 (
    .a(m20),
    .b(m23),
    .out(m31)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:179.10-179.31" *)
  sbox_and and13 (
    .a(m27),
    .b(m31),
    .out(m32)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:181.10-181.31" *)
  sbox_and and14 (
    .a(m21),
    .b(m22),
    .out(m34)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:182.10-182.31" *)
  sbox_and and15 (
    .a(m24),
    .b(m34),
    .out(m35)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:193.10-193.30" *)
  sbox_and and16 (
    .a(m44),
    .b(t6),
    .out(m46)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:194.10-194.30" *)
  sbox_and and17 (
    .a(m40),
    .b(t8),
    .out(m47)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:195.10-195.29" *)
  sbox_and and18 (
    .a(m39),
    .b(d),
    .out(m48)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:196.10-196.31" *)
  sbox_and and19 (
    .a(m43),
    .b(t16),
    .out(m49)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:151.10-151.27" *)
  sbox_and and2 (
    .a(t19),
    .b(d),
    .out(m4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:197.10-197.30" *)
  sbox_and and20 (
    .a(m38),
    .b(t9),
    .out(m50)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:198.10-198.31" *)
  sbox_and and21 (
    .a(m37),
    .b(t17),
    .out(m51)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:199.10-199.31" *)
  sbox_and and22 (
    .a(m42),
    .b(t15),
    .out(m52)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:200.10-200.31" *)
  sbox_and and23 (
    .a(m45),
    .b(t27),
    .out(m53)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:201.10-201.31" *)
  sbox_and and24 (
    .a(m41),
    .b(t10),
    .out(m54)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:202.10-202.31" *)
  sbox_and and25 (
    .a(m44),
    .b(t13),
    .out(m55)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:203.10-203.31" *)
  sbox_and and26 (
    .a(m40),
    .b(t23),
    .out(m56)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:204.10-204.31" *)
  sbox_and and27 (
    .a(m39),
    .b(t19),
    .out(m57)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:205.10-205.30" *)
  sbox_and and28 (
    .a(m43),
    .b(t3),
    .out(m58)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:206.10-206.31" *)
  sbox_and and29 (
    .a(m38),
    .b(t22),
    .out(m59)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:153.10-153.28" *)
  sbox_and and3 (
    .a(t3),
    .b(t16),
    .out(m6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:207.10-207.31" *)
  sbox_and and30 (
    .a(m37),
    .b(t20),
    .out(m60)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:208.10-208.30" *)
  sbox_and and31 (
    .a(m42),
    .b(t1),
    .out(m61)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:209.10-209.30" *)
  sbox_and and32 (
    .a(m45),
    .b(t4),
    .out(m62)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:210.10-210.30" *)
  sbox_and and33 (
    .a(m41),
    .b(t2),
    .out(m63)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:154.10-154.28" *)
  sbox_and and4 (
    .a(t22),
    .b(t9),
    .out(m7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:156.10-156.29" *)
  sbox_and and5 (
    .a(t20),
    .b(t17),
    .out(m9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:158.10-158.29" *)
  sbox_and and6 (
    .a(t1),
    .b(t15),
    .out(m11)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:159.10-159.29" *)
  sbox_and and7 (
    .a(t4),
    .b(t27),
    .out(m12)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:161.10-161.29" *)
  sbox_and and8 (
    .a(t2),
    .b(t10),
    .out(m14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:172.10-172.31" *)
  sbox_and and9 (
    .a(m22),
    .b(m20),
    .out(m25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:244.11-244.32" *)
  sbox_xnor fxnor0 (
    .a(l16),
    .b(l26),
    .out(s1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:245.11-245.32" *)
  sbox_xnor fxnor1 (
    .a(l19),
    .b(l28),
    .out(s2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:249.11-249.32" *)
  sbox_xnor fxnor2 (
    .a(l13),
    .b(l27),
    .out(s6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:250.11-250.31" *)
  sbox_xnor fxnor3 (
    .a(l6),
    .b(l23),
    .out(s7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:24.10-24.29" *)
  sbox_xor fxor0 (
    .a(u0),
    .b(u3),
    .out(ft1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:25.10-25.29" *)
  sbox_xor fxor1 (
    .a(u0),
    .b(u5),
    .out(ft2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:34.10-34.31" *)
  sbox_xor fxor10 (
    .a(u1),
    .b(u5),
    .out(ft11)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:35.10-35.31" *)
  sbox_xor fxor11 (
    .a(u2),
    .b(u5),
    .out(ft12)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:36.10-36.33" *)
  sbox_xor fxor12 (
    .a(ft3),
    .b(ft4),
    .out(ft13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:37.10-37.34" *)
  sbox_xor fxor13 (
    .a(ft6),
    .b(ft11),
    .out(ft14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:38.10-38.34" *)
  sbox_xor fxor14 (
    .a(ft5),
    .b(ft11),
    .out(ft15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:39.10-39.34" *)
  sbox_xor fxor15 (
    .a(ft5),
    .b(ft12),
    .out(ft16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:40.10-40.34" *)
  sbox_xor fxor16 (
    .a(ft9),
    .b(ft16),
    .out(ft17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:41.10-41.31" *)
  sbox_xor fxor17 (
    .a(u3),
    .b(u7),
    .out(ft18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:42.10-42.34" *)
  sbox_xor fxor18 (
    .a(ft7),
    .b(ft18),
    .out(ft19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:43.10-43.34" *)
  sbox_xor fxor19 (
    .a(ft1),
    .b(ft19),
    .out(ft20)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:26.10-26.29" *)
  sbox_xor fxor2 (
    .a(u0),
    .b(u6),
    .out(ft3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:44.10-44.31" *)
  sbox_xor fxor20 (
    .a(u6),
    .b(u7),
    .out(ft21)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:45.10-45.34" *)
  sbox_xor fxor21 (
    .a(ft7),
    .b(ft21),
    .out(ft22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:46.10-46.34" *)
  sbox_xor fxor22 (
    .a(ft2),
    .b(ft22),
    .out(ft23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:47.10-47.34" *)
  sbox_xor fxor23 (
    .a(ft2),
    .b(ft10),
    .out(ft24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:48.10-48.35" *)
  sbox_xor fxor24 (
    .a(ft20),
    .b(ft17),
    .out(ft25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:49.10-49.34" *)
  sbox_xor fxor25 (
    .a(ft3),
    .b(ft16),
    .out(ft26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:50.10-50.34" *)
  sbox_xor fxor26 (
    .a(ft1),
    .b(ft12),
    .out(ft27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:213.10-213.31" *)
  sbox_xor fxor27 (
    .a(m61),
    .b(m62),
    .out(l0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:214.10-214.31" *)
  sbox_xor fxor28 (
    .a(m50),
    .b(m56),
    .out(l1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:215.10-215.31" *)
  sbox_xor fxor29 (
    .a(m46),
    .b(m48),
    .out(l2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:27.10-27.29" *)
  sbox_xor fxor3 (
    .a(u3),
    .b(u5),
    .out(ft4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:216.10-216.31" *)
  sbox_xor fxor30 (
    .a(m47),
    .b(m55),
    .out(l3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:217.10-217.31" *)
  sbox_xor fxor31 (
    .a(m54),
    .b(m58),
    .out(l4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:218.10-218.31" *)
  sbox_xor fxor32 (
    .a(m49),
    .b(m61),
    .out(l5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:219.10-219.30" *)
  sbox_xor fxor33 (
    .a(m62),
    .b(l5),
    .out(l6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:220.10-220.30" *)
  sbox_xor fxor34 (
    .a(m46),
    .b(l3),
    .out(l7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:221.10-221.31" *)
  sbox_xor fxor35 (
    .a(m51),
    .b(m59),
    .out(l8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:222.10-222.31" *)
  sbox_xor fxor36 (
    .a(m52),
    .b(m53),
    .out(l9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:223.10-223.31" *)
  sbox_xor fxor37 (
    .a(m53),
    .b(l4),
    .out(l10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:224.10-224.31" *)
  sbox_xor fxor38 (
    .a(m60),
    .b(l2),
    .out(l11)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:225.10-225.32" *)
  sbox_xor fxor39 (
    .a(m48),
    .b(m51),
    .out(l12)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:28.10-28.29" *)
  sbox_xor fxor4 (
    .a(u4),
    .b(u6),
    .out(ft5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:226.10-226.31" *)
  sbox_xor fxor40 (
    .a(m50),
    .b(l0),
    .out(l13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:227.10-227.32" *)
  sbox_xor fxor41 (
    .a(m52),
    .b(m61),
    .out(l14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:228.10-228.31" *)
  sbox_xor fxor42 (
    .a(m55),
    .b(l1),
    .out(l15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:229.10-229.31" *)
  sbox_xor fxor43 (
    .a(m56),
    .b(l0),
    .out(l16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:230.10-230.31" *)
  sbox_xor fxor44 (
    .a(m57),
    .b(l1),
    .out(l17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:231.10-231.31" *)
  sbox_xor fxor45 (
    .a(m58),
    .b(l8),
    .out(l18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:232.10-232.31" *)
  sbox_xor fxor46 (
    .a(m63),
    .b(l4),
    .out(l19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:233.10-233.30" *)
  sbox_xor fxor47 (
    .a(l0),
    .b(l1),
    .out(l20)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:234.10-234.30" *)
  sbox_xor fxor48 (
    .a(l1),
    .b(l7),
    .out(l21)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:235.10-235.31" *)
  sbox_xor fxor49 (
    .a(l3),
    .b(l12),
    .out(l22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:29.10-29.31" *)
  sbox_xor fxor5 (
    .a(ft1),
    .b(ft5),
    .out(ft6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:236.10-236.31" *)
  sbox_xor fxor50 (
    .a(l18),
    .b(l2),
    .out(l23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:237.10-237.31" *)
  sbox_xor fxor51 (
    .a(l15),
    .b(l9),
    .out(l24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:238.10-238.31" *)
  sbox_xor fxor52 (
    .a(l6),
    .b(l10),
    .out(l25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:239.10-239.30" *)
  sbox_xor fxor53 (
    .a(l7),
    .b(l9),
    .out(l26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:240.10-240.31" *)
  sbox_xor fxor54 (
    .a(l8),
    .b(l10),
    .out(l27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:241.10-241.32" *)
  sbox_xor fxor55 (
    .a(l11),
    .b(l14),
    .out(l28)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:242.10-242.32" *)
  sbox_xor fxor56 (
    .a(l11),
    .b(l17),
    .out(l29)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:243.10-243.30" *)
  sbox_xor fxor57 (
    .a(l6),
    .b(l24),
    .out(s0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:246.10-246.30" *)
  sbox_xor fxor58 (
    .a(l6),
    .b(l21),
    .out(s3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:247.10-247.31" *)
  sbox_xor fxor59 (
    .a(l20),
    .b(l22),
    .out(s4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:30.10-30.29" *)
  sbox_xor fxor6 (
    .a(u1),
    .b(u2),
    .out(ft7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:248.10-248.31" *)
  sbox_xor fxor60 (
    .a(l25),
    .b(l29),
    .out(s5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:31.10-31.30" *)
  sbox_xor fxor7 (
    .a(u7),
    .b(ft6),
    .out(ft8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:32.10-32.30" *)
  sbox_xor fxor8 (
    .a(u7),
    .b(ft7),
    .out(ft9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:33.10-33.32" *)
  sbox_xor fxor9 (
    .a(ft6),
    .b(ft7),
    .out(ft10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:54.11-54.31" *)
  sbox_xnor xnor0 (
    .a(u1),
    .b(u3),
    .out(rt22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:55.11-55.30" *)
  sbox_xnor xnor1 (
    .a(u0),
    .b(u1),
    .out(rt2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:57.11-57.31" *)
  sbox_xnor xnor2 (
    .a(u4),
    .b(u7),
    .out(rt24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:59.11-59.32" *)
  sbox_xnor xnor3 (
    .a(u1),
    .b(rt23),
    .out(rt8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:61.11-61.31" *)
  sbox_xnor xnor4 (
    .a(u7),
    .b(rt1),
    .out(rt9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:65.11-65.32" *)
  sbox_xnor xnor5 (
    .a(u2),
    .b(rt1),
    .out(rt25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:67.11-67.33" *)
  sbox_xnor xnor6 (
    .a(u2),
    .b(rt19),
    .out(rt17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:70.11-70.30" *)
  sbox_xnor xnor7 (
    .a(u2),
    .b(u5),
    .out(r17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:71.11-71.30" *)
  sbox_xnor xnor8 (
    .a(u5),
    .b(u6),
    .out(r18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:72.11-72.30" *)
  sbox_xnor xnor9 (
    .a(u2),
    .b(u4),
    .out(r19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:53.10-53.29" *)
  sbox_xor xor0 (
    .a(u0),
    .b(u3),
    .out(rt23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:56.10-56.28" *)
  sbox_xor xor1 (
    .a(u3),
    .b(u4),
    .out(rt1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:73.10-73.29" *)
  sbox_xor xor10 (
    .a(u0),
    .b(r17),
    .out(y5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:74.10-74.32" *)
  sbox_xor xor11 (
    .a(rt22),
    .b(r17),
    .out(rt6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:75.10-75.32" *)
  sbox_xor xor12 (
    .a(r13),
    .b(r19),
    .out(rt16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:76.10-76.32" *)
  sbox_xor xor13 (
    .a(rt1),
    .b(r18),
    .out(rt27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:77.10-77.34" *)
  sbox_xor xor14 (
    .a(rt10),
    .b(rt27),
    .out(rt15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:78.10-78.33" *)
  sbox_xor xor15 (
    .a(rt10),
    .b(r18),
    .out(rt14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:79.10-79.33" *)
  sbox_xor xor16 (
    .a(rt3),
    .b(rt16),
    .out(rt26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:150.10-150.29" *)
  sbox_xor xor17 (
    .a(t14),
    .b(m1),
    .out(m3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:152.10-152.28" *)
  sbox_xor xor18 (
    .a(m4),
    .b(m1),
    .out(m5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:155.10-155.29" *)
  sbox_xor xor19 (
    .a(t26),
    .b(m6),
    .out(m8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:58.10-58.27" *)
  sbox_xor xor2 (
    .a(u6),
    .b(u7),
    .out(r5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:157.10-157.29" *)
  sbox_xor xor20 (
    .a(m9),
    .b(m6),
    .out(m10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:160.10-160.31" *)
  sbox_xor xor21 (
    .a(m12),
    .b(m11),
    .out(m13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:162.10-162.31" *)
  sbox_xor xor22 (
    .a(m14),
    .b(m11),
    .out(m15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:163.10-163.29" *)
  sbox_xor xor23 (
    .a(m3),
    .b(m2),
    .out(m16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:164.10-164.30" *)
  sbox_xor xor24 (
    .a(m5),
    .b(t24),
    .out(m17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:165.10-165.29" *)
  sbox_xor xor25 (
    .a(m8),
    .b(m7),
    .out(m18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:166.10-166.31" *)
  sbox_xor xor26 (
    .a(m10),
    .b(m15),
    .out(m19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:167.10-167.31" *)
  sbox_xor xor27 (
    .a(m16),
    .b(m13),
    .out(m20)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:168.10-168.31" *)
  sbox_xor xor28 (
    .a(m17),
    .b(m15),
    .out(m21)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:169.10-169.31" *)
  sbox_xor xor29 (
    .a(m18),
    .b(m13),
    .out(m22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:60.10-60.31" *)
  sbox_xor xor3 (
    .a(rt22),
    .b(r5),
    .out(rt19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:170.10-170.31" *)
  sbox_xor xor30 (
    .a(m19),
    .b(t25),
    .out(m23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:171.10-171.31" *)
  sbox_xor xor31 (
    .a(m22),
    .b(m23),
    .out(m24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:173.10-173.31" *)
  sbox_xor xor32 (
    .a(m21),
    .b(m25),
    .out(m26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:174.10-174.31" *)
  sbox_xor xor33 (
    .a(m20),
    .b(m21),
    .out(m27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:175.10-175.31" *)
  sbox_xor xor34 (
    .a(m23),
    .b(m25),
    .out(m28)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:180.10-180.31" *)
  sbox_xor xor35 (
    .a(m27),
    .b(m25),
    .out(m33)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:183.10-183.31" *)
  sbox_xor xor36 (
    .a(m24),
    .b(m25),
    .out(m36)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:184.10-184.31" *)
  sbox_xor xor37 (
    .a(m21),
    .b(m29),
    .out(m37)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:185.10-185.31" *)
  sbox_xor xor38 (
    .a(m32),
    .b(m33),
    .out(m38)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:186.10-186.31" *)
  sbox_xor xor39 (
    .a(m23),
    .b(m30),
    .out(m39)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:62.10-62.32" *)
  sbox_xor xor4 (
    .a(rt2),
    .b(rt24),
    .out(rt10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:187.10-187.31" *)
  sbox_xor xor40 (
    .a(m35),
    .b(m36),
    .out(m40)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:188.10-188.31" *)
  sbox_xor xor41 (
    .a(m38),
    .b(m40),
    .out(m41)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:189.10-189.31" *)
  sbox_xor xor42 (
    .a(m37),
    .b(m39),
    .out(m42)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:190.10-190.31" *)
  sbox_xor xor43 (
    .a(m37),
    .b(m38),
    .out(m43)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:191.10-191.31" *)
  sbox_xor xor44 (
    .a(m39),
    .b(m40),
    .out(m44)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:192.10-192.31" *)
  sbox_xor xor45 (
    .a(m42),
    .b(m41),
    .out(m45)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:253.10-253.30" *)
  sbox_xor xor46 (
    .a(m52),
    .b(m61),
    .out(p0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:254.10-254.30" *)
  sbox_xor xor47 (
    .a(m58),
    .b(m59),
    .out(p1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:255.10-255.30" *)
  sbox_xor xor48 (
    .a(m54),
    .b(m62),
    .out(p2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:256.10-256.30" *)
  sbox_xor xor49 (
    .a(m47),
    .b(m50),
    .out(p3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:63.10-63.30" *)
  sbox_xor xor5 (
    .a(rt2),
    .b(r5),
    .out(rt13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:257.10-257.30" *)
  sbox_xor xor50 (
    .a(m48),
    .b(m56),
    .out(p4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:258.10-258.30" *)
  sbox_xor xor51 (
    .a(m46),
    .b(m51),
    .out(p5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:259.10-259.30" *)
  sbox_xor xor52 (
    .a(m49),
    .b(m60),
    .out(p6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:260.10-260.28" *)
  sbox_xor xor53 (
    .a(p0),
    .b(p1),
    .out(p7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:261.10-261.30" *)
  sbox_xor xor54 (
    .a(m50),
    .b(m53),
    .out(p8)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:262.10-262.30" *)
  sbox_xor xor55 (
    .a(m55),
    .b(m63),
    .out(p9)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:263.10-263.30" *)
  sbox_xor xor56 (
    .a(m57),
    .b(p4),
    .out(p10)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:264.10-264.29" *)
  sbox_xor xor57 (
    .a(p0),
    .b(p3),
    .out(p11)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:265.10-265.31" *)
  sbox_xor xor58 (
    .a(m46),
    .b(m48),
    .out(p12)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:266.10-266.31" *)
  sbox_xor xor59 (
    .a(m49),
    .b(m51),
    .out(p13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:64.10-64.29" *)
  sbox_xor xor6 (
    .a(rt1),
    .b(r5),
    .out(rt3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:267.10-267.31" *)
  sbox_xor xor60 (
    .a(m49),
    .b(m62),
    .out(p14)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:268.10-268.31" *)
  sbox_xor xor61 (
    .a(m54),
    .b(m59),
    .out(p15)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:269.10-269.31" *)
  sbox_xor xor62 (
    .a(m57),
    .b(m61),
    .out(p16)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:270.10-270.30" *)
  sbox_xor xor63 (
    .a(m58),
    .b(p2),
    .out(p17)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:271.10-271.30" *)
  sbox_xor xor64 (
    .a(m63),
    .b(p5),
    .out(p18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:272.10-272.29" *)
  sbox_xor xor65 (
    .a(p2),
    .b(p3),
    .out(p19)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:273.10-273.29" *)
  sbox_xor xor66 (
    .a(p4),
    .b(p6),
    .out(p20)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:274.10-274.29" *)
  sbox_xor xor67 (
    .a(p2),
    .b(p7),
    .out(p22)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:275.10-275.29" *)
  sbox_xor xor68 (
    .a(p7),
    .b(p8),
    .out(p23)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:276.10-276.29" *)
  sbox_xor xor69 (
    .a(p5),
    .b(p7),
    .out(p24)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:66.10-66.28" *)
  sbox_xor xor7 (
    .a(u1),
    .b(u6),
    .out(r13)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:277.10-277.30" *)
  sbox_xor xor70 (
    .a(p6),
    .b(p10),
    .out(p25)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:278.10-278.30" *)
  sbox_xor xor71 (
    .a(p9),
    .b(p11),
    .out(p26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:279.10-279.31" *)
  sbox_xor xor72 (
    .a(p10),
    .b(p18),
    .out(p27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:280.10-280.31" *)
  sbox_xor xor73 (
    .a(p11),
    .b(p25),
    .out(p28)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:281.10-281.31" *)
  sbox_xor xor74 (
    .a(p15),
    .b(p20),
    .out(p29)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:282.10-282.30" *)
  sbox_xor xor75 (
    .a(p13),
    .b(p22),
    .out(w0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:283.10-283.30" *)
  sbox_xor xor76 (
    .a(p26),
    .b(p29),
    .out(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:284.10-284.30" *)
  sbox_xor xor77 (
    .a(p17),
    .b(p28),
    .out(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:285.10-285.30" *)
  sbox_xor xor78 (
    .a(p12),
    .b(p22),
    .out(w3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:286.10-286.30" *)
  sbox_xor xor79 (
    .a(p23),
    .b(p27),
    .out(w4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:68.10-68.32" *)
  sbox_xor xor8 (
    .a(rt24),
    .b(r13),
    .out(rt20)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:287.10-287.30" *)
  sbox_xor xor80 (
    .a(p19),
    .b(p24),
    .out(w5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:288.10-288.30" *)
  sbox_xor xor81 (
    .a(p14),
    .b(p23),
    .out(w6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:289.10-289.29" *)
  sbox_xor xor82 (
    .a(p9),
    .b(p16),
    .out(w7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sbox_complete.v:69.10-69.29" *)
  sbox_xor xor9 (
    .a(u4),
    .b(rt8),
    .out(rt4)
  );
endmodule

(* src = "sbox_complete.v:302.1-310.10" *)
module sbox_xnor(a, b, out);
  (* src = "sbox_complete.v:304.11-304.12" *)
  input a;
  wire a;
  (* src = "sbox_complete.v:304.14-304.15" *)
  input b;
  wire b;
  (* src = "sbox_complete.v:305.12-305.15" *)
  output out;
  wire out;
  assign out = ~(a ^ b);
endmodule

(* src = "sbox_complete.v:312.1-320.10" *)
module sbox_xor(a, b, out);
  (* src = "sbox_complete.v:314.11-314.12" *)
  input a;
  wire a;
  (* src = "sbox_complete.v:314.14-314.15" *)
  input b;
  wire b;
  (* src = "sbox_complete.v:315.12-315.15" *)
  output out;
  wire out;
  assign out = a ^ b;
endmodule
